# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Aaron A. Rich
description:
  Front-End Developer working in Atlanta, GA - Specializing in building websites and consulting for small businesses.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dev.aaronarich.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:year/:month/:title/
author: Aaron A. Rich
social:
  name: Aaron A. Rich
  links:
      - https://github.com/aaronarich
      - https://twitter.com/aaronarich
      - https://instagram.com/aaronarich/
twitter_username: aaronarich
github_username:  aaronarich

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jekyll-admin
