---
title: Aaron A. Rich
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Front-End Developer working in Atlanta, GA - Specializing in building
  websites and consulting for small businesses.
baseurl: ''
url: https://aaronarich.com
permalink: "/:categories/:year/:month/:title/"
author: Aaron A. Rich
social:
  name: Aaron A. Rich
  links:
  - https://github.com/aaronarich
  - https://twitter.com/aaronarich
  - https://instagram.com/aaronarich/
twitter_username: aaronarich
github_username: aaronarich
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-seo-tag
- jekyll-sitemap
