#!/usr/bin/env bash
# Regenerates _sass/v1/_tachyons.scss: compiles the full Tachyons framework
# from _sass/scss/ and keeps only the selectors referenced by the site's
# templates, content, and scripts.
#
# Run this whenever you start using a Tachyons class that isn't already in
# the purged file. Requires Node (uses npx for dart-sass and PurgeCSS).
set -euo pipefail
cd "$(dirname "$0")/.."

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Entry file importing every Tachyons module (mirrors upstream tachyons-sass).
{
  for m in normalize colors media-queries box-sizing aspect-ratios images \
           background-size background-position outlines borders border-colors \
           border-radius border-style border-widths box-shadow code coordinates \
           clears display flexbox floats font-family font-style font-weight \
           forms heights letter-spacing line-height links lists max-widths \
           widths overflow position opacity rotations skins skins-pseudo \
           spacing negative-margins tables text-decoration text-align \
           text-transform type-scale typography utilities visibility \
           white-space vertical-align hovers z-index nested styles; do
    echo "@import \"scss/$m\";"
  done
} > "$TMP/full.scss"

npx -y sass --quiet --no-source-map --load-path=_sass "$TMP/full.scss" "$TMP/full.css"

npx -y purgecss \
  --css "$TMP/full.css" \
  --content '_layouts/**/*.html' '_includes/**/*.html' '_posts/**/*.md' \
            './*.md' './*.html' 'assets/js/*.js' \
  --output "$TMP/out"

{
  echo "/* Purged subset of Tachyons (https://tachyons.io) — generated by scripts/purge-tachyons.sh; do not edit by hand. */"
  cat "$TMP/out/full.css"
} > _sass/v1/_tachyons.scss

echo "Wrote _sass/v1/_tachyons.scss ($(wc -c < _sass/v1/_tachyons.scss) bytes)"
